version: '3.7'

services:
    subdomain1:
        build:
          context: .
        container_name: subdomain1
        ports:
          - "${SUBDOMAIN1_HOST_HTTP_PORT}:80"
          - "${SUBDOMAIN1_HOST_HTTPS_PORT}:443"
        volumes:
          - ./www/subdomain1:/home/drixlerangelo/www/subdomain1
          - ${APACHE_DOCKER_SETUP}/subdomain1.net.conf:/etc/apache2/sites-enabled/subdomain1.net.conf
          - ${SSL_SETUP}:/var/imported/ssl
        networks:
            drix_net:
                ipv4_address: 192.168.112.1
    subdomain2:
        build:
          context: .
        container_name: subdomain2
        ports:
          - "${SUBDOMAIN2_HOST_HTTP_PORT}:80"
          - "${SUBDOMAIN2_HOST_HTTPS_PORT}:443"
        volumes:
          - ./www/subdomain2:/home/drixlerangelo/www/subdomain2
          - ${APACHE_DOCKER_SETUP}/subdomain2.net.conf:/etc/apache2/sites-enabled/subdomain2.net.conf
          - ${SSL_SETUP}:/var/imported/ssl
        networks:
            drix_net:
                ipv4_address: 192.168.112.2

networks:
    drix_net:
        driver: bridge
        ipam:
            driver: default
            config:
                - subnet: 192.168.112.0/16
